from typing import Protocol, runtime_checkable

from src.domain.aggregates.proxy.entities import Proxy
from src.domain.user_agent.entities import UserAgent


@runtime_checkable
class WebInstagramClient(Protocol):
    """Интерфейс клиента Instagram"""

    async def __aenter__(self) -> "WebInstagramClient": ...

    async def __aexit__(self, exc_type, exc_val, exc_tb): ...

    async def close(self): ...

    def set_proxy(self, proxy: Proxy) -> None: ...

    def set_user_agent(self, user_agent: UserAgent) -> None: ...

    def set_user_agent_mobile(self, user_agent: UserAgent) -> None: ...

    def get_cookies(self) -> dict: ...

    async def request_reset_password(self, username: str, email: str) -> None: ...

    async def change_password_by_link(
        self,
        password: str,
        reset_password_url: str,
    ) -> bool: ...

    async def send_verification_code_for_auth_platform_challenge(
        self,
        code: str,
        challenge_path: str,
    ): ...

    async def follow_user(self, user_id: str): ...

    async def like_media(self, media_id: str): ...

    async def authorize_by_login_and_password(self, username: str, password: str): ...
    async def authorize_by_sessionid(self, sessionid: str): ...
