from typing import List, Protocol
from uuid import UUID

from src.domain.working_group.entities.working_group.entity import WorkingGroup


class WorkingGroupRepository(Protocol):

    async def acquire_by_id(
        self, working_group_id: UUID, skip_locked=False
    ) -> WorkingGroup | None: ...
    async def get_by_name(self, name: str) -> WorkingGroup | None: ...
    async def get(self) -> List[WorkingGroup]: ...
    async def get_all(self) -> List[WorkingGroup]: ...
    async def get_by_id(self, working_group_id: UUID) -> WorkingGroup | None: ...
    async def create(self, entity: WorkingGroup) -> WorkingGroup: ...
    async def update(self, entity: WorkingGroup) -> None: ...
    async def delete(self, working_group_id: UUID) -> None: ...
